<?php
/**
 * Nichoir
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Lpo Rest
 *
 * Service web pour gérer les oiseaux et nichoirs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Nichoir Class Doc Comment
 *
 * @category    Class
 * @description nichoirs
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Nichoir implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'nichoir';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'nom' => 'string',
        'photo' => 'string',
        'date_installation' => '\DateTime',
        'geolocalisation' => '\Swagger\Client\Model\Geolocalisation',
        'adherent' => '\Swagger\Client\Model\Adherent'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'nom' => null,
        'photo' => 'string',
        'date_installation' => 'date-time',
        'geolocalisation' => null,
        'adherent' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'nom' => 'nom',
        'photo' => 'photo',
        'date_installation' => 'dateInstallation',
        'geolocalisation' => 'geolocalisation',
        'adherent' => 'adherent'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'nom' => 'setNom',
        'photo' => 'setPhoto',
        'date_installation' => 'setDateInstallation',
        'geolocalisation' => 'setGeolocalisation',
        'adherent' => 'setAdherent'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'nom' => 'getNom',
        'photo' => 'getPhoto',
        'date_installation' => 'getDateInstallation',
        'geolocalisation' => 'getGeolocalisation',
        'adherent' => 'getAdherent'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['nom'] = isset($data['nom']) ? $data['nom'] : null;
        $this->container['photo'] = isset($data['photo']) ? $data['photo'] : null;
        $this->container['date_installation'] = isset($data['date_installation']) ? $data['date_installation'] : null;
        $this->container['geolocalisation'] = isset($data['geolocalisation']) ? $data['geolocalisation'] : null;
        $this->container['adherent'] = isset($data['adherent']) ? $data['adherent'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets nom
     * @return string
     */
    public function getNom()
    {
        return $this->container['nom'];
    }

    /**
     * Sets nom
     * @param string $nom
     * @return $this
     */
    public function setNom($nom)
    {
        $this->container['nom'] = $nom;

        return $this;
    }

    /**
     * Gets photo
     * @return string
     */
    public function getPhoto()
    {
        return $this->container['photo'];
    }

    /**
     * Sets photo
     * @param string $photo
     * @return $this
     */
    public function setPhoto($photo)
    {
        $this->container['photo'] = $photo;

        return $this;
    }

    /**
     * Gets date_installation
     * @return \DateTime
     */
    public function getDateInstallation()
    {
        return $this->container['date_installation'];
    }

    /**
     * Sets date_installation
     * @param \DateTime $date_installation
     * @return $this
     */
    public function setDateInstallation($date_installation)
    {
        $this->container['date_installation'] = $date_installation;

        return $this;
    }

    /**
     * Gets geolocalisation
     * @return \Swagger\Client\Model\Geolocalisation
     */
    public function getGeolocalisation()
    {
        return $this->container['geolocalisation'];
    }

    /**
     * Sets geolocalisation
     * @param \Swagger\Client\Model\Geolocalisation $geolocalisation
     * @return $this
     */
    public function setGeolocalisation($geolocalisation)
    {
        $this->container['geolocalisation'] = $geolocalisation;

        return $this;
    }

    /**
     * Gets adherent
     * @return \Swagger\Client\Model\Adherent
     */
    public function getAdherent()
    {
        return $this->container['adherent'];
    }

    /**
     * Sets adherent
     * @param \Swagger\Client\Model\Adherent $adherent
     * @return $this
     */
    public function setAdherent($adherent)
    {
        $this->container['adherent'] = $adherent;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


